### ISSUE TITLE
allow ones to set an Array parameter in config

### ISSUE THREAD

**Issue by kojisekig** [NLP4L/framework#38]

**Comment by kharal5** [comment]
Let me clarify my understanding.

Even if you write like:
```
  settings : {
    fields: ["id", "category", "body"]
  }
```

Thoses settings are treated as String in ProcessorChainBuilder like:
```
    val gSettings: Map[String, String] =
      if(config.hasPath("settings")) {
        config.getConfig("settings").entrySet().map(f => f.getKey -> f.getValue.unwrapped().toString()).toMap
      }
      else Map()
```
 I think we could change the code without doing toString() like:
```
    val gSettings: Map[String, Any] =
     ...
        config.getConfig("settings").entrySet().map(f => f.getKey -> f.getValue.unwrapped()).toMap

```
However , any setting must be declared and used as Map[String, Any], in the Processor, DictionaryAttributeFactory, and so on.

"Any" type is somewhat which is difficult to handle.
There are opinions on the pros and cons of this choice.

I would like to hear some opinions.

Thanks.

**Comment by kharal5** [comment]
For now, one of the solution is to split manually in your code like:

```
 settings : {
    fields: "id, category, body"
    fields2: ["id", "category", "body"]
  }

 val fields: Array[String] = settings("fields").split(",").map(_.trim)

 val fields2: Array[String] = settings("fields2").replaceAll("\\[","").replaceAll("\\]","").split(",").map(_.trim)

note1: 
"field2" is once parsed as array and then converted toString, so that double-quote are removed.
note2: 
Do not use comma in the item name.

```

**Comment by kojisekig** [comment]
I think we should use Config type for settings argument instead of using Map[String,String] or Map[String,Any].

I committed my idea at https://github.com/NLP4L/framework/commit/8158184fcae023a1e40f20b0c92a60b201f08704

Can you take a look at it?

**Comment by kojisekig** [comment]
Hmm, I accidentally included another PR at https://github.com/NLP4L/framework/pull/82/commits/735dfbb21efc0d7ed86dec826509578c7dbbc11c

It shouldn't be included.

**Comment by kojisekig** [comment]
I made another PR that doesn't include different issue which was accidentally included in the previous PR.

I'll merge it to master soon.
