### ISSUE TITLE
allow ones to use regex for filters

### ISSUE THREAD

**Issue by kojisekig** [NLP4L/framework#39]

**Comment by kojisekig** [comment]
As filter stuff uses database search function, it is difficult to allow regex. Instead, let's use like-search.

**Comment by yamamoto-takashi** [comment]
Added the wildcard filtering in result data table.

You can use wildcard at begin and end in filter text box, such like "aaa*", "*aaa", "*aaa*".

Please check add_wildcard_in_filter branch.
