### ISSUE TITLE
allow ones to upload a config file which has no validators and/or deployers

### ISSUE THREAD

**Issue by kojisekig** [NLP4L/framework#41]
It should be possible for users to upload config files which have no validators and/or deployers.

Framework must not display Validate and/or Deploy buttons if there is no validators/deployers in config file.

**Comment by yamamoto-takashi** [comment]
This feature is supported in button_view_control branch.
Please check it.

**Comment by kojisekig** [comment]
I confirmed that it works correctly. Merged #59. Thanks!
