### ISSUE TITLE
solrSearchResult.scala.html must have pagination

### ISSUE THREAD

**Issue by kojisekig** [NLP4L/framework#61]

**Comment by kojisekig** [comment]
Yamamoto-san,

I tried to implement this, but not succeeded yet. A message "No matching records found" appears in the table. It seems that the table doesn't call the address described at "data-url".

I pushed the draft branch to issue_61. I appreciate it if you would see the branch.

BTW, do I need to have searchresult.coffee for this function?

Thanks in advance.

**Comment by yamamoto-takashi** [comment]
OK, I will see the issue_61 branch.

**Comment by kojisekig** [comment]
merged yesterday
